
###
# @name nvc
POST https://connect-apps.ceh.ac.uk/ESHAAPI/nvc
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "input_tvks": [
    "NBNSYS0000004445",
    "NHMSYS0000457103"
  ]
}