export default {
  'Pollen & Nectar': [
    'Filipendula ulmaria',
    'Leontodon autumnalis',
    'Oenanthe silaifolia',
    'Persicaria bistorta',
    'Sanguisorba officinalis',
    'Silaum silaus',
    'Succisa pratensis',
    'Thalictrum flavum',
    'Centaurea nigra',
    'Filipendula vulgaris',
    'Galium verum',
    'Lathyrus pratensis',
    'Leucanthemum vulgare',
    'Lotus corniculatus',
    'Primula veris',
    'Rhinanthus minor',
    'Serratula tinctoria',
    'Stachys officinalis',
    'Tragopogon pratensis',
  ],
  'Flood-plain grasslands MG4': [
    'Filipendula ulmaria',
    'Leontodon autumnalis',
    'Oenanthe silaifolia',
    'Persicaria bistorta',
    'Sanguisorba officinalis',
    'Silaum silaus',
    'Succisa pratensis',
    'Thalictrum flavum',
    'Centaurea nigra',
    'Filipendula vulgaris',
    'Galium verum',
    'Lathyrus pratensis',
    'Leucanthemum vulgare',
    'Lotus corniculatus',
    'Primula veris',
    'Rhinanthus minor',
    'Serratula tinctoria',
    'Stachys officinalis',
    'Tragopogon pratensis',
  ],
  'Wet grasslands MG8': [
    'Achillea ptarmica',
    'Berula erecta',
    'Caltha palustris',
    'Cardamine pratensis',
    'Cirsium dissectum',
    'Eupatorium cannabinum',
    'Filipendula ulmaria',
    'Galium palustre/G. uliginosum',
    'Geum rivale',
    'Hydrocotyle vulgaris',
    'Lotus pedunculatus',
    'Lychnis flos-cuculi',
    'Mentha aquatica',
    'Orchidaceae spp.',
    'Potentilla palustris',
    'Ranunculus flammula',
    'small blue-green Carex spp. (leaves less than 5mm wide) (=C. flaccaC.nigraC.panicea)',
    'Succisa pratensis',
    'Thalictrum flavum',
    'Valeriana dioica',
    'Viola palustris',
  ],
};
